# Generated by Django 3.2.5 on 2021-08-02 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='salary',
            field=models.CharField(default='Negotiateable', max_length=50),
            preserve_default=False,
        ),
    ]
